
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PaymentMethod = {
  DINHEIRO: 'DINHEIRO',
  PIX: 'PIX',
  CARTAO_DE_CREDITO: 'CARTAO_DE_CREDITO',
  CARTAO_DEBITO: 'CARTAO_DEBITO'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const SaleStatus = {
  PAGO: 'PAGO',
  PENDENTE: 'PENDENTE'
} as const

export type SaleStatus = (typeof SaleStatus)[keyof typeof SaleStatus]
